name: Build MRS

on:
  push:
    paths:
      - "mihomo/domain/*.list"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download mihomo
        run: |
          mkdir -p mihomo-bin

          URL=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/latest \
            | grep browser_download_url \
            | grep linux-amd64 \
            | cut -d '"' -f 4 | head -n 1)

          curl -L "$URL" -o mihomo.tar.gz
          tar -xzf mihomo.tar.gz -C mihomo-bin
          chmod +x mihomo-bin/mihomo

      - name: Build MRS
        run: |
          mkdir -p mihomo/mrs

          BIN=$(find mihomo-bin -type f -name mihomo | head -n 1)
          chmod +x "$BIN"

          for file in mihomo/domain/*.list; do
            name=$(basename "$file" .list)
            "$BIN" convert-ruleset domain text "$file" "mihomo/mrs/$name.mrs"
          done

          for file in mihomo/domain/*.list; do
            name=$(basename "$file" .list)
            ./mihomo-bin/mihomo convert-ruleset domain text "$file" "mihomo/mrs/$name.mrs"
          done

      - name: Commit MRS
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add mihomo/mrs/*.mrs

          git commit -m "build mrs" || exit 0
          git push
